model_name: qcnet
root: /scratch/dalbesio/dataset
train_batch_size: 4 # 4
val_batch_size: 4 # 4
test_batch_size: 4 # 4
dataset: argoverse_v2 
num_historical_steps: 50 
num_future_steps: 60 
num_recurrent_steps: 3 
pl2pl_radius: 150 
time_span: 10 
pl2a_radius: 50 
a2a_radius: 50 
num_t2m_steps: 30 
pl2m_radius: 150 
a2m_radius: 150
input_dim: 2
hidden_dim: 128
output_dim: 2
output_head: true
num_modes: 6
num_freq_bands: 64
num_map_layers: 1
num_agent_layers: 2
num_dec_layers: 2
num_heads: 8
head_dim: 16
dropout: 0.1
max_epochs: 100
grad_clip_norm: 5.0
lr: 0.0001
weight_decay: 0.0
T_max: 64